spring:
  application:
    name: reaktor-images-cloner-client
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
server:
  port: 8094
logging:
    level:
        root: INFO
    file:
        name: /tmp/reaktor_imagesClonerClient.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB

reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://somos.iesjandula.es
  images_cloner_server_url: https://api.iesjandula.es/
  firebase_server_url: https://api.iesjandula.es/
  notifications_server_url: https://api.iesjandula.es/
  school_base_server_url: https://api.iesjandula.es/
  clientId: ${CLIENT_ID}
  http_connection_timeout: 30000
  clonezilla:
    root: /opt/clonezilla-http
    images-dir: images
  audit:
    exchange: audit.exchange
    routing-key: audit.key